
@echo off

REM !!! Generated by the fmp-cli 1.62.0.  DO NOT EDIT!

md SecretDock\Assets\3rd\fmp-xtc-secretdock

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-secretdock-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\SecretDock\Assets\3rd\fmp-xtc-secretdock\
